server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: device_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/devices/**
          filters:
            - StripPrefix=2
        - id: order_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/orders/**
          filters:
            - StripPrefix=2
        - id: payment_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/payments/**
          filters:
            - StripPrefix=2
        - id: report_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/report/**
          filters:
            - StripPrefix=2
#kafka config
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

tps:
  topic-name: tps-report-topic
